
name: docs
on:
  push:
    paths:
      - "docs/**"
      - "**/*.md"
permissions:
  contents: read
jobs:
  docs-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docs Gardener
        uses: YOUR_ORG/llm-action@v1
        with:
          endpoint: ${{ secrets.LLM_ENDPOINT }}
          api_key: ${{ secrets.LLM_API_KEY }}
          model: YOUR_MODEL
          system_prompt: ${{ secrets.DOCS_GARDENER_SYSTEM_PROMPT }}
          input_json: '{"changed_files": "${{ toJson(github.event) }}"}'
