
name: security
on:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 3 * * *"
permissions:
  contents: read
  security-events: write
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency scan (example)
        uses: github/ghas-some-action@v1
      - name: LLM Security Review (advisory summary)
        uses: YOUR_ORG/llm-action@v1
        with:
          endpoint: ${{ secrets.LLM_ENDPOINT }}
          api_key: ${{ secrets.LLM_API_KEY }}
          model: YOUR_MODEL
          system_prompt: ${{ secrets.SECURITY_SENTINEL_SYSTEM_PROMPT }}
          input_json: ${{ toJson(github) }}
