replicaCount: 2
image:
  repository: ghcr.io/your-org/csam-guard
  tag: "14.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  PROMETHEUS_ENABLED: "1"
  NLP_ENABLED: "0"
  TRUST_XFF: "1"
  HASH_LIST_PATH: "/app/data/known_hashes.json"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: csam-guard.local
      paths:
        - path: /
          pathType: Prefix
