name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -U pip
      - run: pip install ruff mypy pre-commit
      - run: ruff check .
      - run: mypy --ignore-missing-imports .
      - run: pre-commit run --all-files
