name: release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  build-publish:
    permissions: { contents: write, id-token: write }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -U pip build twine
      - run: python -m build
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
